// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ApiKeyCreate'
} as const;

export const ApiKeyCreateResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        api_key_id: {
            type: 'string',
            format: 'uuid',
            title: 'Api Key Id'
        },
        key_string: {
            type: 'string',
            title: 'Key String'
        }
    },
    type: 'object',
    required: [
        'name',
        'api_key_id',
        'key_string'
    ],
    title: 'ApiKeyCreateResponse'
} as const;

export const ApiKeyResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        api_key_id: {
            type: 'string',
            format: 'uuid',
            title: 'Api Key Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'api_key_id'
    ],
    title: 'ApiKeyResponse'
} as const;

export const ApiKeySecretLinkCreateSchema = {
    properties: {
        api_key_id: {
            type: 'string',
            format: 'uuid',
            title: 'Api Key Id'
        },
        secret_id: {
            type: 'string',
            format: 'uuid',
            title: 'Secret Id'
        }
    },
    type: 'object',
    required: [
        'api_key_id',
        'secret_id'
    ],
    title: 'ApiKeySecretLinkCreate'
} as const;

export const ApiKeySecretLinkResponseSchema = {
    properties: {
        api_key_id: {
            type: 'string',
            format: 'uuid',
            title: 'Api Key Id'
        },
        secret_id: {
            type: 'string',
            format: 'uuid',
            title: 'Secret Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'api_key_id',
        'secret_id',
        'id'
    ],
    title: 'ApiKeySecretLinkResponse'
} as const;

export const ApiMeResponseSchema = {
    properties: {
        is_admin: {
            type: 'boolean',
            title: 'Is Admin'
        }
    },
    type: 'object',
    required: [
        'is_admin'
    ],
    title: 'ApiMeResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const SecretCreateSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        secret: {
            type: 'string',
            title: 'Secret'
        }
    },
    type: 'object',
    required: [
        'key',
        'secret'
    ],
    title: 'SecretCreate'
} as const;

export const SecretListResponseSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        secret_id: {
            type: 'string',
            format: 'uuid',
            title: 'Secret Id'
        }
    },
    type: 'object',
    required: [
        'key',
        'secret_id'
    ],
    title: 'SecretListResponse'
} as const;

export const SecretResponseSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        secret_id: {
            type: 'string',
            format: 'uuid',
            title: 'Secret Id'
        },
        secret: {
            type: 'string',
            title: 'Secret'
        }
    },
    type: 'object',
    required: [
        'key',
        'secret_id',
        'secret'
    ],
    title: 'SecretResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
