// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateKeyApiV1AdminApiKeysPostData, CreateKeyApiV1AdminApiKeysPostErrors, CreateKeyApiV1AdminApiKeysPostResponses, CreateLinkApiV1AdminLinksPostData, CreateLinkApiV1AdminLinksPostErrors, CreateLinkApiV1AdminLinksPostResponses, CreateSecApiV1AdminSecretsPostData, CreateSecApiV1AdminSecretsPostErrors, CreateSecApiV1AdminSecretsPostResponses, DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteData, DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteErrors, DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponses, DeleteLinkApiV1AdminLinksLinkIdDeleteData, DeleteLinkApiV1AdminLinksLinkIdDeleteErrors, DeleteLinkApiV1AdminLinksLinkIdDeleteResponses, DeleteSecApiV1AdminSecretsSecretIdDeleteData, DeleteSecApiV1AdminSecretsSecretIdDeleteErrors, DeleteSecApiV1AdminSecretsSecretIdDeleteResponses, ReadKeysApiV1AdminApiKeysGetData, ReadKeysApiV1AdminApiKeysGetErrors, ReadKeysApiV1AdminApiKeysGetResponses, ReadLinksApiV1AdminLinksGetData, ReadLinksApiV1AdminLinksGetErrors, ReadLinksApiV1AdminLinksGetResponses, ReadMyKeyApiV1ClientMeGetData, ReadMyKeyApiV1ClientMeGetResponses, ReadMySecretApiV1ClientSecretsKeyGetData, ReadMySecretApiV1ClientSecretsKeyGetErrors, ReadMySecretApiV1ClientSecretsKeyGetResponses, ReadMySecretsApiV1ClientSecretsGetData, ReadMySecretsApiV1ClientSecretsGetResponses, ReadRootApiV1HealthGetData, ReadRootApiV1HealthGetResponses, ReadSecsApiV1AdminSecretsGetData, ReadSecsApiV1AdminSecretsGetErrors, ReadSecsApiV1AdminSecretsGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Keys
 */
export const readKeysApiV1AdminApiKeysGet = <ThrowOnError extends boolean = false>(options?: Options<ReadKeysApiV1AdminApiKeysGetData, ThrowOnError>) => (options?.client ?? client).get<ReadKeysApiV1AdminApiKeysGetResponses, ReadKeysApiV1AdminApiKeysGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/api-keys/',
    ...options
});

/**
 * Create Key
 */
export const createKeyApiV1AdminApiKeysPost = <ThrowOnError extends boolean = false>(options: Options<CreateKeyApiV1AdminApiKeysPostData, ThrowOnError>) => (options.client ?? client).post<CreateKeyApiV1AdminApiKeysPostResponses, CreateKeyApiV1AdminApiKeysPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/api-keys/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Key
 */
export const deleteKeyApiV1AdminApiKeysApiKeyIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponses, DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/api-keys/{api_key_id}',
    ...options
});

/**
 * Read Secs
 */
export const readSecsApiV1AdminSecretsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadSecsApiV1AdminSecretsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadSecsApiV1AdminSecretsGetResponses, ReadSecsApiV1AdminSecretsGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/secrets/',
    ...options
});

/**
 * Create Sec
 */
export const createSecApiV1AdminSecretsPost = <ThrowOnError extends boolean = false>(options: Options<CreateSecApiV1AdminSecretsPostData, ThrowOnError>) => (options.client ?? client).post<CreateSecApiV1AdminSecretsPostResponses, CreateSecApiV1AdminSecretsPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/secrets/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Sec
 */
export const deleteSecApiV1AdminSecretsSecretIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteSecApiV1AdminSecretsSecretIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteSecApiV1AdminSecretsSecretIdDeleteResponses, DeleteSecApiV1AdminSecretsSecretIdDeleteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/secrets/{secret_id}',
    ...options
});

/**
 * Read Links
 */
export const readLinksApiV1AdminLinksGet = <ThrowOnError extends boolean = false>(options?: Options<ReadLinksApiV1AdminLinksGetData, ThrowOnError>) => (options?.client ?? client).get<ReadLinksApiV1AdminLinksGetResponses, ReadLinksApiV1AdminLinksGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/links/',
    ...options
});

/**
 * Create Link
 */
export const createLinkApiV1AdminLinksPost = <ThrowOnError extends boolean = false>(options: Options<CreateLinkApiV1AdminLinksPostData, ThrowOnError>) => (options.client ?? client).post<CreateLinkApiV1AdminLinksPostResponses, CreateLinkApiV1AdminLinksPostErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/links/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Link
 */
export const deleteLinkApiV1AdminLinksLinkIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteLinkApiV1AdminLinksLinkIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteLinkApiV1AdminLinksLinkIdDeleteResponses, DeleteLinkApiV1AdminLinksLinkIdDeleteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/admin/links/{link_id}',
    ...options
});

/**
 * Read My Key
 */
export const readMyKeyApiV1ClientMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMyKeyApiV1ClientMeGetData, ThrowOnError>) => (options?.client ?? client).get<ReadMyKeyApiV1ClientMeGetResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/client/me',
    ...options
});

/**
 * Read My Secrets
 */
export const readMySecretsApiV1ClientSecretsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMySecretsApiV1ClientSecretsGetData, ThrowOnError>) => (options?.client ?? client).get<ReadMySecretsApiV1ClientSecretsGetResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/client/secrets',
    ...options
});

/**
 * Read My Secret
 */
export const readMySecretApiV1ClientSecretsKeyGet = <ThrowOnError extends boolean = false>(options: Options<ReadMySecretApiV1ClientSecretsKeyGetData, ThrowOnError>) => (options.client ?? client).get<ReadMySecretApiV1ClientSecretsKeyGetResponses, ReadMySecretApiV1ClientSecretsKeyGetErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/client/secrets/{key}',
    ...options
});

/**
 * Read Root
 */
export const readRootApiV1HealthGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootApiV1HealthGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootApiV1HealthGetResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });
