// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
};

/**
 * ApiKeyCreateResponse
 */
export type ApiKeyCreateResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
    /**
     * Api Key Id
     */
    api_key_id: string;
    /**
     * Key String
     */
    key_string: string;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
    /**
     * Api Key Id
     */
    api_key_id: string;
};

/**
 * ApiKeySecretLinkCreate
 */
export type ApiKeySecretLinkCreate = {
    /**
     * Api Key Id
     */
    api_key_id: string;
    /**
     * Secret Id
     */
    secret_id: string;
};

/**
 * ApiKeySecretLinkResponse
 */
export type ApiKeySecretLinkResponse = {
    /**
     * Api Key Id
     */
    api_key_id: string;
    /**
     * Secret Id
     */
    secret_id: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ApiMeResponse
 */
export type ApiMeResponse = {
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SecretCreate
 */
export type SecretCreate = {
    /**
     * Key
     */
    key: string;
    /**
     * Secret
     */
    secret: string;
};

/**
 * SecretResponse
 */
export type SecretResponse = {
    /**
     * Key
     */
    key: string;
    /**
     * Secret
     */
    secret: string;
    /**
     * Secret Id
     */
    secret_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadKeysApiV1AdminApiKeysGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/api-keys/';
};

export type ReadKeysApiV1AdminApiKeysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadKeysApiV1AdminApiKeysGetError = ReadKeysApiV1AdminApiKeysGetErrors[keyof ReadKeysApiV1AdminApiKeysGetErrors];

export type ReadKeysApiV1AdminApiKeysGetResponses = {
    /**
     * Response Read Keys Api V1 Admin Api Keys  Get
     *
     * Successful Response
     */
    200: Array<ApiKeyResponse>;
};

export type ReadKeysApiV1AdminApiKeysGetResponse = ReadKeysApiV1AdminApiKeysGetResponses[keyof ReadKeysApiV1AdminApiKeysGetResponses];

export type CreateKeyApiV1AdminApiKeysPostData = {
    body: ApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/api-keys/';
};

export type CreateKeyApiV1AdminApiKeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKeyApiV1AdminApiKeysPostError = CreateKeyApiV1AdminApiKeysPostErrors[keyof CreateKeyApiV1AdminApiKeysPostErrors];

export type CreateKeyApiV1AdminApiKeysPostResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyCreateResponse;
};

export type CreateKeyApiV1AdminApiKeysPostResponse = CreateKeyApiV1AdminApiKeysPostResponses[keyof CreateKeyApiV1AdminApiKeysPostResponses];

export type DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Api Key Id
         */
        api_key_id: string;
    };
    query?: never;
    url: '/api/v1/admin/api-keys/{api_key_id}';
};

export type DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteError = DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteErrors[keyof DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteErrors];

export type DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponses = {
    /**
     * Response Delete Key Api V1 Admin Api Keys  Api Key Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponse = DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponses[keyof DeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponses];

export type ReadSecsApiV1AdminSecretsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/secrets/';
};

export type ReadSecsApiV1AdminSecretsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSecsApiV1AdminSecretsGetError = ReadSecsApiV1AdminSecretsGetErrors[keyof ReadSecsApiV1AdminSecretsGetErrors];

export type ReadSecsApiV1AdminSecretsGetResponses = {
    /**
     * Response Read Secs Api V1 Admin Secrets  Get
     *
     * Successful Response
     */
    200: Array<SecretResponse>;
};

export type ReadSecsApiV1AdminSecretsGetResponse = ReadSecsApiV1AdminSecretsGetResponses[keyof ReadSecsApiV1AdminSecretsGetResponses];

export type CreateSecApiV1AdminSecretsPostData = {
    body: SecretCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/secrets/';
};

export type CreateSecApiV1AdminSecretsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSecApiV1AdminSecretsPostError = CreateSecApiV1AdminSecretsPostErrors[keyof CreateSecApiV1AdminSecretsPostErrors];

export type CreateSecApiV1AdminSecretsPostResponses = {
    /**
     * Successful Response
     */
    200: SecretResponse;
};

export type CreateSecApiV1AdminSecretsPostResponse = CreateSecApiV1AdminSecretsPostResponses[keyof CreateSecApiV1AdminSecretsPostResponses];

export type DeleteSecApiV1AdminSecretsSecretIdDeleteData = {
    body?: never;
    path: {
        /**
         * Secret Id
         */
        secret_id: string;
    };
    query?: never;
    url: '/api/v1/admin/secrets/{secret_id}';
};

export type DeleteSecApiV1AdminSecretsSecretIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSecApiV1AdminSecretsSecretIdDeleteError = DeleteSecApiV1AdminSecretsSecretIdDeleteErrors[keyof DeleteSecApiV1AdminSecretsSecretIdDeleteErrors];

export type DeleteSecApiV1AdminSecretsSecretIdDeleteResponses = {
    /**
     * Response Delete Sec Api V1 Admin Secrets  Secret Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteSecApiV1AdminSecretsSecretIdDeleteResponse = DeleteSecApiV1AdminSecretsSecretIdDeleteResponses[keyof DeleteSecApiV1AdminSecretsSecretIdDeleteResponses];

export type ReadLinksApiV1AdminLinksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/links/';
};

export type ReadLinksApiV1AdminLinksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadLinksApiV1AdminLinksGetError = ReadLinksApiV1AdminLinksGetErrors[keyof ReadLinksApiV1AdminLinksGetErrors];

export type ReadLinksApiV1AdminLinksGetResponses = {
    /**
     * Response Read Links Api V1 Admin Links  Get
     *
     * Successful Response
     */
    200: Array<ApiKeySecretLinkResponse>;
};

export type ReadLinksApiV1AdminLinksGetResponse = ReadLinksApiV1AdminLinksGetResponses[keyof ReadLinksApiV1AdminLinksGetResponses];

export type CreateLinkApiV1AdminLinksPostData = {
    body: ApiKeySecretLinkCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/links/';
};

export type CreateLinkApiV1AdminLinksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLinkApiV1AdminLinksPostError = CreateLinkApiV1AdminLinksPostErrors[keyof CreateLinkApiV1AdminLinksPostErrors];

export type CreateLinkApiV1AdminLinksPostResponses = {
    /**
     * Successful Response
     */
    200: ApiKeySecretLinkResponse;
};

export type CreateLinkApiV1AdminLinksPostResponse = CreateLinkApiV1AdminLinksPostResponses[keyof CreateLinkApiV1AdminLinksPostResponses];

export type DeleteLinkApiV1AdminLinksLinkIdDeleteData = {
    body?: never;
    path: {
        /**
         * Link Id
         */
        link_id: string;
    };
    query?: never;
    url: '/api/v1/admin/links/{link_id}';
};

export type DeleteLinkApiV1AdminLinksLinkIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLinkApiV1AdminLinksLinkIdDeleteError = DeleteLinkApiV1AdminLinksLinkIdDeleteErrors[keyof DeleteLinkApiV1AdminLinksLinkIdDeleteErrors];

export type DeleteLinkApiV1AdminLinksLinkIdDeleteResponses = {
    /**
     * Response Delete Link Api V1 Admin Links  Link Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteLinkApiV1AdminLinksLinkIdDeleteResponse = DeleteLinkApiV1AdminLinksLinkIdDeleteResponses[keyof DeleteLinkApiV1AdminLinksLinkIdDeleteResponses];

export type ReadMyKeyApiV1ClientMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/client/me';
};

export type ReadMyKeyApiV1ClientMeGetResponses = {
    /**
     * Successful Response
     */
    200: ApiMeResponse;
};

export type ReadMyKeyApiV1ClientMeGetResponse = ReadMyKeyApiV1ClientMeGetResponses[keyof ReadMyKeyApiV1ClientMeGetResponses];

export type ReadMySecretsApiV1ClientSecretsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/client/secrets';
};

export type ReadMySecretsApiV1ClientSecretsGetResponses = {
    /**
     * Response Read My Secrets Api V1 Client Secrets Get
     *
     * Successful Response
     */
    200: Array<SecretResponse>;
};

export type ReadMySecretsApiV1ClientSecretsGetResponse = ReadMySecretsApiV1ClientSecretsGetResponses[keyof ReadMySecretsApiV1ClientSecretsGetResponses];

export type ReadMySecretApiV1ClientSecretsKeyGetData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/v1/client/secrets/{key}';
};

export type ReadMySecretApiV1ClientSecretsKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMySecretApiV1ClientSecretsKeyGetError = ReadMySecretApiV1ClientSecretsKeyGetErrors[keyof ReadMySecretApiV1ClientSecretsKeyGetErrors];

export type ReadMySecretApiV1ClientSecretsKeyGetResponses = {
    /**
     * Successful Response
     */
    200: SecretResponse;
};

export type ReadMySecretApiV1ClientSecretsKeyGetResponse = ReadMySecretApiV1ClientSecretsKeyGetResponses[keyof ReadMySecretApiV1ClientSecretsKeyGetResponses];

export type ReadRootApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type ReadRootApiV1HealthGetResponses = {
    /**
     * Response Read Root Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadRootApiV1HealthGetResponse = ReadRootApiV1HealthGetResponses[keyof ReadRootApiV1HealthGetResponses];
