// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ApiKeyCreate
 */
export const zApiKeyCreate = z.object({
    name: z.string(),
    is_admin: z.boolean().optional().default(false)
});

/**
 * ApiKeyCreateResponse
 */
export const zApiKeyCreateResponse = z.object({
    name: z.string(),
    is_admin: z.boolean().optional().default(false),
    api_key_id: z.uuid(),
    key_string: z.string()
});

/**
 * ApiKeyResponse
 */
export const zApiKeyResponse = z.object({
    name: z.string(),
    is_admin: z.boolean().optional().default(false),
    api_key_id: z.uuid()
});

/**
 * ApiKeySecretLinkCreate
 */
export const zApiKeySecretLinkCreate = z.object({
    api_key_id: z.uuid(),
    secret_id: z.uuid()
});

/**
 * ApiKeySecretLinkResponse
 */
export const zApiKeySecretLinkResponse = z.object({
    api_key_id: z.uuid(),
    secret_id: z.uuid(),
    id: z.uuid()
});

/**
 * ApiMeResponse
 */
export const zApiMeResponse = z.object({
    is_admin: z.boolean(),
    name: z.string()
});

/**
 * SecretCreate
 */
export const zSecretCreate = z.object({
    key: z.string(),
    secret: z.string()
});

/**
 * SecretListResponse
 */
export const zSecretListResponse = z.object({
    key: z.string(),
    secret_id: z.uuid()
});

/**
 * SecretResponse
 */
export const zSecretResponse = z.object({
    key: z.string(),
    secret_id: z.uuid(),
    secret: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zReadKeysApiV1AdminApiKeysGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100)
    }).optional()
});

/**
 * Response Read Keys Api V1 Admin Api Keys  Get
 *
 * Successful Response
 */
export const zReadKeysApiV1AdminApiKeysGetResponse = z.array(zApiKeyResponse);

export const zCreateKeyApiV1AdminApiKeysPostData = z.object({
    body: zApiKeyCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateKeyApiV1AdminApiKeysPostResponse = zApiKeyCreateResponse;

export const zDeleteKeyApiV1AdminApiKeysApiKeyIdDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        api_key_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Response Delete Key Api V1 Admin Api Keys  Api Key Id  Delete
 *
 * Successful Response
 */
export const zDeleteKeyApiV1AdminApiKeysApiKeyIdDeleteResponse = z.record(z.string(), z.string());

export const zReadKeyApiV1AdminApiKeysApiKeyIdGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        api_key_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zReadKeyApiV1AdminApiKeysApiKeyIdGetResponse = zApiKeyResponse;

export const zReadSecsApiV1AdminSecretsGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100),
        for_api_key_id: z.uuid().nullish()
    }).optional()
});

/**
 * Response Read Secs Api V1 Admin Secrets  Get
 *
 * Successful Response
 */
export const zReadSecsApiV1AdminSecretsGetResponse = z.array(zSecretListResponse);

export const zCreateSecApiV1AdminSecretsPostData = z.object({
    body: zSecretCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateSecApiV1AdminSecretsPostResponse = zSecretResponse;

export const zDeleteSecApiV1AdminSecretsSecretIdDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        secret_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Response Delete Sec Api V1 Admin Secrets  Secret Id  Delete
 *
 * Successful Response
 */
export const zDeleteSecApiV1AdminSecretsSecretIdDeleteResponse = z.record(z.string(), z.string());

export const zReadSecApiV1AdminSecretsSecretIdGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        secret_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zReadSecApiV1AdminSecretsSecretIdGetResponse = zSecretResponse;

export const zReadLinksApiV1AdminLinksGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100)
    }).optional()
});

/**
 * Response Read Links Api V1 Admin Links  Get
 *
 * Successful Response
 */
export const zReadLinksApiV1AdminLinksGetResponse = z.array(zApiKeySecretLinkResponse);

export const zCreateLinkApiV1AdminLinksPostData = z.object({
    body: zApiKeySecretLinkCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateLinkApiV1AdminLinksPostResponse = zApiKeySecretLinkResponse;

export const zDeleteLinkApiV1AdminLinksLinkIdDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        link_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Response Delete Link Api V1 Admin Links  Link Id  Delete
 *
 * Successful Response
 */
export const zDeleteLinkApiV1AdminLinksLinkIdDeleteResponse = z.record(z.string(), z.string());

export const zReadAvailableSecretsApiV1AdminLinksAvailableSecretsApiKeyIdGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        api_key_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Response Read Available Secrets Api V1 Admin Links Available Secrets  Api Key Id  Get
 *
 * Successful Response
 */
export const zReadAvailableSecretsApiV1AdminLinksAvailableSecretsApiKeyIdGetResponse = z.array(zSecretResponse);

export const zReadMyKeyApiV1ClientMeGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zReadMyKeyApiV1ClientMeGetResponse = zApiMeResponse;

export const zReadMySecretsApiV1ClientSecretsGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Read My Secrets Api V1 Client Secrets Get
 *
 * Successful Response
 */
export const zReadMySecretsApiV1ClientSecretsGetResponse = z.array(zSecretListResponse);

export const zReadMySecretApiV1ClientSecretsKeyGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        key: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zReadMySecretApiV1ClientSecretsKeyGetResponse = zSecretResponse;

export const zReadRootApiV1HealthGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Read Root Api V1 Health Get
 *
 * Successful Response
 */
export const zReadRootApiV1HealthGetResponse = z.record(z.string(), z.string());
