"""initial

Revision ID: 77966d4ca9a1
Revises: 
Create Date: 2026-03-23 23:57:18.518846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77966d4ca9a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_api_key', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=True)
    op.create_table('secrets',
    sa.Column('secret_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('secret_id')
    )
    op.create_index(op.f('ix_secrets_key'), 'secrets', ['key'], unique=True)
    op.create_table('api_key_secrets_link',
    sa.Column('link_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('secret_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.api_key_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.secret_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key_secrets_link')
    op.drop_index(op.f('ix_secrets_key'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
