"""add_unique_link_constraint

Revision ID: f4e14f0d0700
Revises: 77966d4ca9a1
Create Date: 2026-03-24 00:30:09.536593

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4e14f0d0700'
down_revision: str | Sequence[str] | None = '77966d4ca9a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_api_key_secret', 'api_key_secrets_link', ['api_key_id', 'secret_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_api_key_secret', 'api_key_secrets_link', type_='unique')
    # ### end Alembic commands ###
